export const prepareNatoAnswer = (letter) => {
  switch (letter.toLowerCase()) {
    case "a": return "ALPHA"
    case "b": return "BRAVO"
    case "c": return "CHARLIE"
    case "d": return "DELTA"
    case "e": return "ECHO"
    case "f": return "FOXTROT"
    case "g": return "GOLF"
    case "h": return "HOTEL"
    case "i": return "INDIA"
    case "j": return "JULIET"
    case "k": return "KILO"
    case "l": return "LIMA"
    case "m": return "MIKE"
    case "n": return "NOVEMBER"
    case "o": return "OSCAR"
    case "p": return "PAPA"
    case "q": return "QUEBEC"
    case "r": return "ROMEO"
    case "s": return "SIERRA"
    case "t": return "TANGO"
    case "u": return "UNIFORM"
    case "v": return "VICTOR"
    case "w": return "WHISKEY"
    case "x": return "XRAY"
    case "y": return "YANKEE"
    case "z": return "ZULU";
  }
}